version: '3.9'

volumes:
  db:

services:
  postgres:
    image: postgres
    # restart: always
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
       POSTGRES_PASSWORD: qwe123qwe
    networks:
      psnet:
        ipv4_address: 10.5.0.5

  jagergroupis:
    image: ${DOCKER_REGISTRY-}jagergroupis
    # restart: always
    build:
      context: .
      dockerfile: JagerGroupIS/Dockerfile
    environment:
      LANG: ru_RU.UTF-8
      LC_ALL: ru_RU.UTF-8
      TZ: Europe/Moscow
    networks:
      - psnet
    depends_on:
      - postgres
    links:
      - postgres 

networks:
  psnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
