version: '3.9'

services:
  firebird:
    image: controlsoft/firebird
    # restart: always
    container_name: firebird
    ports:
      - 3050:3050
      - 3051:3051
    volumes:
      - C:\databases:/databases # Windows
      - /home/user/databases:/databases # Linux
    environment:
      - PASSWORD=masterkey
    networks:
      - fbnet
      
    # healthcheck:
    #   test: ["CMD-SHELL", "gstat"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  jagergroupis:
    image: ${DOCKER_REGISTRY-}jagergroupis
    restart: always
    build:
      context: .
      dockerfile: JagerGroupIS/Dockerfile
    environment:
      LANG: ru_RU.UTF-8
      LC_ALL: ru_RU.UTF-8
      TZ: Europe/Moscow
    networks:
      - fbnet

networks:
  fbnet:
    driver: bridge

    # depends_on:
    #   firebird: 
    #     condition: service_healthy

  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_DB: testdb
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready --dbname=testdb --username=admin"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   ports:
  #     - "5432:5432"


